name: Run Playwright Tests
permissions:
  contents: write

on:
  # push:
  #   branches: [ main ]
  # pull_request:
    workflow_dispatch:   # cho phép bấm chạy tay
    schedule:
    - cron: '0 19 * * 3'
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Install Playwright browsers
      run: pwsh bin/Debug/net8.0/playwright.ps1 install
    - name: Run specific test class
      run: ./run-by-module.sh
      
    - name: Generate Allure Report
      run: |
          npm install -g allure-commandline --save-dev
          allure open allure-report  

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
  

    